projectTdd/appTdd/urls.py
from django.urls import *
from .views import index

app_name = "appTdd"

urlpatterns = [
    path('', index, name="index"),
    ]

projectTdd/projectTdd/urls.py
from django.contrib import admin
from django.urls import path, include
import appTdd.urls as appTdd

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("appTdd.urls")),
]

projectTdd/appTdd/models.py
# Create your models here.
from django.db import models
from django.utils import timezone

class TddModel(models.Model):
    my_status = models.CharField(max_length=300)
    my_time = models.DateTimeField(auto_now_add=True)

projectTdd/appTdd/forms.py
from django import forms

class Tdd_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }
    my_status = forms.CharField(max_length=30, widget=forms.TextInput(attrs=attrs))
    

projectTdd/appTdd/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Tdd_Form
from .models import TddModel

# Create your views here.

response = {}

def index(request):
    response["listform"]= Tdd_Form
    myform= TddModel.objects.all()
    response["Tdd_Form"]= myform

    form= Tdd_Form(request.POST or None)
    if(request.method == "POST" and form.is_valid()):
        response['my_status'] = request.POST['my_status']
        myform  = TddModel(my_status = response['my_status'])
        myform.save()
        return render(request, 'tdd.html', response)
    else:
        return render(request, 'tdd.html', response)
                           
                        

projectTdd/appTdd/templates/tdd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Title</title>
</head>
<body>
<h1>Hello, Apa Kabar?</h1>


<div>
    <form id="form" method="POST" action ="{% url 'appTdd:index' %}">
        {% csrf_token %}
        {% for field in listform %}
            {{ field.label_tag }}
            <br>
            {{field}}

        {% endfor %}
        <br>
        <button type="submit" id="button" class="btn btn2 btn-success">Submit </button>
    </form>
</div>
<div class = "container">
    {% for result in Tdd_Form %}
    <div>
        <h5>Date: {{result.my_time}}</h5>
        <h5>Status: {{result.my_status}}</h5>
    </div>
    {% endfor %}
</div>

</body>
</html>